"""Shared enums used across models, schemas and services.

Kept in one place so the print-job status machine (Section 9.4 of the
design doc) and driver/artifact types stay consistent everywhere.
"""

from __future__ import annotations

import enum


class UserRole(str, enum.Enum):
    ADMIN = "ADMIN"
    USER = "USER"


class PrinterDriverType(str, enum.Enum):
    BAMBU_LAN = "BAMBU_LAN"
    OCTOPRINT = "OCTOPRINT"
    MOONRAKER = "MOONRAKER"
    DUMMY = "DUMMY"


class PrintJobStatus(str, enum.Enum):
    SUBMITTED = "SUBMITTED"
    REJECTED = "REJECTED"
    APPROVED = "APPROVED"
    QUEUED = "QUEUED"
    READY_TO_PRINT = "READY_TO_PRINT"
    SLICING = "SLICING"
    SLICED = "SLICED"
    PRINTING = "PRINTING"
    PAUSED = "PAUSED"
    FINISHED = "FINISHED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    DELETED = "DELETED"


class SlicedArtifactType(str, enum.Enum):
    GCODE_3MF = "GCODE_3MF"
    GCODE = "GCODE"
    PREVIEW = "PREVIEW"
    METADATA_JSON = "METADATA_JSON"


class AuditAction(str, enum.Enum):
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DISABLED = "USER_DISABLED"
    USER_ENABLED = "USER_ENABLED"
    PASSWORD_RESET = "PASSWORD_RESET"
    JOB_SUBMITTED = "JOB_SUBMITTED"
    JOB_APPROVED = "JOB_APPROVED"
    JOB_REJECTED = "JOB_REJECTED"
    JOB_UNAPPROVED = "JOB_UNAPPROVED"
    JOB_ENQUEUED = "JOB_ENQUEUED"
    JOB_REMOVED_FROM_QUEUE = "JOB_REMOVED_FROM_QUEUE"
    QUEUE_REORDERED = "QUEUE_REORDERED"
    SLICING_STARTED = "SLICING_STARTED"
    SLICING_SUCCEEDED = "SLICING_SUCCEEDED"
    SLICING_FAILED = "SLICING_FAILED"
    PRINTER_CREATED = "PRINTER_CREATED"
    PRINTER_UPDATED = "PRINTER_UPDATED"
    PRINT_STARTED = "PRINT_STARTED"
    PRINT_PAUSED = "PRINT_PAUSED"
    PRINT_RESUMED = "PRINT_RESUMED"
    PRINT_CANCELLED = "PRINT_CANCELLED"
    PRINT_FINISHED = "PRINT_FINISHED"
    PRINT_FAILED = "PRINT_FAILED"
    RETENTION_DELETED = "RETENTION_DELETED"
    RETENTION_RUN = "RETENTION_RUN"
    UPDATE_CHECKED = "UPDATE_CHECKED"
    UPDATE_STARTED = "UPDATE_STARTED"
    UPDATE_FAILED = "UPDATE_FAILED"
    SETTINGS_UPDATED = "SETTINGS_UPDATED"
