"""add update_runs table

Revision ID: 0f7c452d333f
Revises: e7d4dddb1e80
Create Date: 2026-07-10 17:13:30.010330

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7c452d333f'
down_revision: Union[str, None] = 'e7d4dddb1e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'update_runs',
        sa.Column(
            'status',
            sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='update_run_status'),
            nullable=False,
        ),
        sa.Column('from_version', sa.String(length=64), nullable=False),
        sa.Column('to_version', sa.String(length=64), nullable=True),
        sa.Column('triggered_by_id', sa.UUID(), nullable=True),
        sa.Column('log', sa.Text(), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###

    # Not auto-detected: a new AuditAction value for the update flow.
    op.execute("ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'UPDATE_SUCCEEDED'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_runs')
    # ### end Alembic commands ###
    # Note: PostgreSQL cannot drop a single enum value, so
    # 'UPDATE_SUCCEEDED' intentionally remains on downgrade.
