"""initial schema

Revision ID: e7d4dddb1e80
Revises: 
Create Date: 2026-07-10 15:46:30.018637

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7d4dddb1e80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printers',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('driver_type', sa.Enum('BAMBU_LAN', 'OCTOPRINT', 'MOONRAKER', 'DUMMY', name='printer_driver_type'), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('access_code_encrypted', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role'), nullable=False),
    sa.Column('class_name', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('USER_CREATED', 'USER_UPDATED', 'USER_DISABLED', 'USER_ENABLED', 'PASSWORD_RESET', 'JOB_SUBMITTED', 'JOB_APPROVED', 'JOB_REJECTED', 'JOB_UNAPPROVED', 'JOB_ENQUEUED', 'JOB_REMOVED_FROM_QUEUE', 'QUEUE_REORDERED', 'SLICING_STARTED', 'SLICING_SUCCEEDED', 'SLICING_FAILED', 'PRINTER_CREATED', 'PRINTER_UPDATED', 'PRINT_STARTED', 'PRINT_PAUSED', 'PRINT_RESUMED', 'PRINT_CANCELLED', 'PRINT_FINISHED', 'PRINT_FAILED', 'RETENTION_DELETED', 'RETENTION_RUN', 'UPDATE_CHECKED', 'UPDATE_STARTED', 'UPDATE_FAILED', 'SETTINGS_UPDATED', name='audit_action'), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_uploaded_files_owner_id'), 'uploaded_files', ['owner_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_sha256'), 'uploaded_files', ['sha256'], unique=False)
    op.create_table('print_jobs',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_file_id', sa.UUID(), nullable=False),
    sa.Column('printer_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'REJECTED', 'APPROVED', 'QUEUED', 'READY_TO_PRINT', 'SLICING', 'SLICED', 'PRINTING', 'PAUSED', 'FINISHED', 'FAILED', 'CANCELLED', 'EXPIRED', 'DELETED', name='print_job_status'), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.Column('teacher_note', sa.Text(), nullable=True),
    sa.Column('student_note', sa.Text(), nullable=True),
    sa.Column('estimated_print_time_seconds', sa.Integer(), nullable=True),
    sa.Column('estimated_filament_grams', sa.Float(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_jobs_owner_id'), 'print_jobs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_print_jobs_printer_id'), 'print_jobs', ['printer_id'], unique=False)
    op.create_index(op.f('ix_print_jobs_queue_position'), 'print_jobs', ['queue_position'], unique=False)
    op.create_index(op.f('ix_print_jobs_status'), 'print_jobs', ['status'], unique=False)
    op.create_table('sliced_artifacts',
    sa.Column('print_job_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('artifact_type', sa.Enum('GCODE_3MF', 'GCODE', 'PREVIEW', 'METADATA_JSON', name='sliced_artifact_type'), nullable=False),
    sa.Column('slicer_name', sa.String(length=64), nullable=False),
    sa.Column('slicer_version', sa.String(length=64), nullable=True),
    sa.Column('profile_name', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['print_job_id'], ['print_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sliced_artifacts_print_job_id'), 'sliced_artifacts', ['print_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sliced_artifacts_print_job_id'), table_name='sliced_artifacts')
    op.drop_table('sliced_artifacts')
    op.drop_index(op.f('ix_print_jobs_status'), table_name='print_jobs')
    op.drop_index(op.f('ix_print_jobs_queue_position'), table_name='print_jobs')
    op.drop_index(op.f('ix_print_jobs_printer_id'), table_name='print_jobs')
    op.drop_index(op.f('ix_print_jobs_owner_id'), table_name='print_jobs')
    op.drop_table('print_jobs')
    op.drop_index(op.f('ix_uploaded_files_sha256'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_owner_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_table('printers')
    # ### end Alembic commands ###
