#!/usr/bin/env python3
"""A stand-in for the real OrcaSlicer CLI binary, used only in tests.

Mimics just enough of the real CLI contract (last two positional-ish
args are `--export-3mf <output>` and `<input.stl>`) to exercise
`app.slicer.runner`/`app.slicer.service` without needing the actual
OrcaSlicer binary, which isn't available in this sandbox.
"""

from __future__ import annotations

import sys
import time
from pathlib import Path

FAKE_GCODE = """; generated by fake_slicer.py for tests
; estimated printing time (normal mode) = 1h 2m 3s
; total filament used [g] = 12.5
G28
G1 X0 Y0 Z0
"""


def main() -> int:
    args = sys.argv[1:]
    output_path = Path(args[args.index("--export-3mf") + 1])
    input_path = Path(args[-1])

    # The uploaded file is stored under a UUID-based name, so we can't use
    # the filename to steer test behavior. Instead we sniff a marker
    # embedded in the (otherwise-unused) binary STL header bytes.
    header = input_path.read_bytes()[:80]

    if b"MARKER_CORRUPT" in header:
        sys.stderr.write("fake_slicer: unable to parse mesh, file appears corrupt\n")
        return 1

    if b"MARKER_HANGS" in header:
        time.sleep(5)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(FAKE_GCODE)
    print(f"fake_slicer: sliced {input_path.name} -> {output_path.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
